Use EShop

---This is a comment
---Get all Products
select * from Product

--Get all Products that have categoryid = 10
select * from Product
Where CategoryId = 10


--Get total cost of Product listed with categoryid = 10
select sum(Cost) from Product
where categoryId = 10

--Get Product name, cost from Product table
Select Name, Cost from Product

---Save above as a view
CREATE VIEW vw_Product AS
(select Name, Cost from Product)

--see the view result
select * from vw_Product

--Get all Products that start with 'K'

select * from Product
where Name Like 'K%'

--Get all Products that have the second character

select * from Product
where Name Like '_e%'

--Get all Product whose cost is not equal to 500

select *  from Product
where Cost <> 5000


--'^%s$' => The word start (^) with any character and contains 's' at the end ($)

select * from Product
where Name LIKE '%K%s'
--Select all Products with name as 'T-Shirt', 'Iphone', 'Kurti'

select * from Product 
where Name = 'T-Shirt'
OR
Name = 'Iphone' 
OR
Name = 'Kurti'


--Beter Technique

select * from Product
where Name in ('T-Shirt', 'Iphone', 'Kurti')


--Get all products having a category id matching a category in ProductCategory table

select *from Product
where CategoryId IN (select Id from ProductCategory)

--Get customer name and order id for all customers
select [Name], [OrderId] from Customer, Orders
where Customer.Id = orders.CustomerId

--Get Total Revenu generated by 'Anush'
--Customer Name from customer table
--Total cost from Product
--Orders table contains Customer purchases

select SUM(Cost)
From Orders, Customer, Product
where Orders.CustomerId = Customer.Id
AND Orders.ProductId = Product.Id
AND Customer.Name = 'Murali'